import './style.css'

const app = document.querySelector('#app')
const state = { username: '', room: null, error: '', selectedColor: null }
const soundState = { context: null, lastTurn: null, lastUnoCall: null, resultPlayed: false }
const socketProtocol = window.location.protocol === 'https:' ? 'wss' : 'ws'
const socketUrl = import.meta.env.VITE_WS_URL || `${socketProtocol}://${window.location.hostname}:3001`
const socket = new WebSocket(socketUrl)

socket.addEventListener('open', () => { const savedUsername = getCookie('runo_username'); if (savedUsername) { state.username = savedUsername; renderLobby() } else renderAuth() })
socket.addEventListener('message', ({ data }) => {
  const message = JSON.parse(data)
  if (message.type === 'error') { state.error = message.message; renderCurrent(); return }
  if (message.type === 'room') { state.room = message.room; state.error = ''; if (message.room.lastUnoCall && message.room.lastUnoCall.nonce !== soundState.lastUnoCall) { soundState.lastUnoCall = message.room.lastUnoCall.nonce; playUnoSound() } renderCurrent() }
})
socket.addEventListener('close', () => { state.error = 'Connection lost. Refresh to reconnect.'; renderCurrent() })

function send(type, payload = {}) { socket.send(JSON.stringify({ type, ...payload })) }
function unlockAudio() { if (!soundState.context) { const AudioContext = window.AudioContext || window.webkitAudioContext; if (!AudioContext) return; soundState.context = new AudioContext() } if (soundState.context.state === 'suspended') soundState.context.resume() }
function playTone(frequency, duration, type = 'sine', volume = 0.045, offset = 0) { const context = soundState.context; if (!context) return; if (context.state === 'suspended') { context.resume().then(() => playTone(frequency, duration, type, volume, offset)); return } if (context.state !== 'running') return; const start = context.currentTime + offset; const oscillator = context.createOscillator(); const gain = context.createGain(); oscillator.type = type; oscillator.frequency.setValueAtTime(frequency, start); gain.gain.setValueAtTime(0.0001, start); gain.gain.exponentialRampToValueAtTime(volume, start + 0.012); gain.gain.exponentialRampToValueAtTime(0.0001, start + duration); oscillator.connect(gain); gain.connect(context.destination); oscillator.start(start); oscillator.stop(start + duration + 0.02) }
function playTurnSound() { playTone(660, 0.12, 'sine', 0.035); playTone(880, 0.16, 'sine', 0.03, 0.1) }
function playRejectSound() { playTone(170, 0.13, 'square', 0.035); playTone(115, 0.16, 'square', 0.025, 0.08) }
function playPlaceSound() { playTone(330, 0.08, 'triangle', 0.04); playTone(520, 0.16, 'triangle', 0.035, 0.06) }
function playDrawSound() { playTone(240, 0.08, 'sine', 0.03); playTone(180, 0.13, 'sine', 0.025, 0.07) }
function playUnoSound() { playTone(230, 0.08, 'sine', 0.035); playTone(185, 0.09, 'sine', 0.032, 0.075); playTone(145, 0.13, 'sine', 0.03, 0.15); playTone(245, 0.16, 'triangle', 0.035, 0.26) }
function playWinSound() { playTone(523, 0.12, 'triangle', 0.04); playTone(659, 0.12, 'triangle', 0.04, 0.1); playTone(784, 0.2, 'triangle', 0.04, 0.2) }
function playLoseSound() { playTone(220, 0.18, 'sine', 0.04); playTone(165, 0.28, 'sine', 0.035, 0.15) }
function renderAuth() {
  app.innerHTML = `<main class="auth-layout">
    <section class="brand-panel"><div class="brand-mark"><span>U</span></div><p class="eyebrow">THE QUICK-FIRE CARD ROOM</p><h1>UNO</h1><p class="intro">A bright, chaotic card table for your favorite people. Pick a name, grab a room, and let the cards decide the rest.</p><div class="mini-stack"><i class="card red">7</i><i class="card yellow">↻</i><i class="card blue">+2</i></div></section>
    <section class="auth-panel"><div class="panel-kicker">WELCOME TO THE TABLE</div><h2>Who’s playing?</h2><p class="muted">Your username appears to everyone in the room.</p><form id="name-form"><label>Display name<input id="username" maxlength="18" required placeholder="e.g. Skyler" autofocus></label><button class="primary wide">Continue <span>→</span></button></form><p class="footnote">No password. No fuss. Just cards.</p></section>
  </main>`
  document.querySelector('#name-form').addEventListener('submit', (event) => { event.preventDefault(); unlockAudio(); state.username = document.querySelector('#username').value.trim(); if (state.username) { setCookie('runo_username', state.username, 365); renderLobby() } })
}
function renderLobby() {
  app.innerHTML = `<main class="lobby-layout"><header class="topbar"><div class="wordmark"><span class="dot"></span> UNO</div><div class="profile"><span class="avatar">${initials(state.username)}</span>${escapeHtml(state.username)}</div></header><section class="lobby-content"><div class="lobby-heading"><div><p class="eyebrow">PRIVATE CARD ROOMS</p><h1>Ready when you are.</h1><p class="muted">Create a room for your crew or enter a code to jump in.</p></div><div class="spark">✦</div></div><div class="room-actions"><form class="room-card create" id="create-form"><div class="room-icon">✦</div><h3>Host a new game</h3><p>Make a room, share the code, and deal the first hand.</p><button class="primary">Create room <span>↗</span></button></form><form class="room-card join" id="join-form"><div class="room-icon">⌁</div><h3>Join your friends</h3><p>Have a room code? You’re one shuffle away.</p><label>Room code<input id="room-code" maxlength="5" placeholder="e.g. A7K2Q" required></label><button class="secondary">Join room <span>→</span></button></form></div>${state.error ? `<p class="error">${escapeHtml(state.error)}</p>` : ''}<div class="lobby-tip"><span>✎</span><div><strong>How it works</strong><br>Each room deals a fresh randomized deck. First player to empty their hand wins.</div></div></section></main>`
  document.querySelector('#create-form').addEventListener('submit', (event) => { event.preventDefault(); unlockAudio(); send('createRoom', { username: state.username }) })
  document.querySelector('#join-form').addEventListener('submit', (event) => { event.preventDefault(); unlockAudio(); send('joinRoom', { username: state.username, code: document.querySelector('#room-code').value.toUpperCase() }) })
}
function renderRoom() {
  const room = state.room
  soundState.lastTurn = null
  if (room.status === 'playing') return renderGame()
  app.innerHTML = `<main class="room-layout"><header class="topbar"><div class="wordmark"><span class="dot"></span> UNO <span class="live-pill">● LIVE ROOM</span></div><button class="ghost" id="leave">Leave room</button></header><section class="waiting"><div class="waiting-copy"><p class="eyebrow">ROOM READY</p><h1>Bring your people<br><em>to the table.</em></h1><p class="muted">Share this code with anyone you want to play with.</p><div class="code-display"><span>${room.code}</span><button id="copy" title="Copy room code">▣</button></div><p class="copy-status" id="copy-status">Anyone with the code can join.</p></div><div class="players-card"><div class="card-title"><span>PLAYERS <b>${room.players.length}/6</b></span><span class="pulse">● open</span></div><div class="player-list">${room.players.map((player, index) => `<div class="player-row"><span class="avatar ${index === 0 ? 'host' : ''}">${initials(player.name)}</span><span>${escapeHtml(player.name)}${index === 0 ? '<small>HOST</small>' : ''}</span><span class="ready-dot">●</span></div>`).join('')}</div><div class="settings-panel"><div class="settings-heading"><span>GAME SETTINGS</span><small>${room.isHost ? 'HOST CONTROLS' : 'HOST CONFIGURED'}</small></div>${settingRow('cardSuggestions', 'Card suggestions', 'Highlight only cards that can be played.', room)}${settingRow('cardStacking', 'Card stacking', 'Stack +2 and +4 penalties with no limit.', room)}${settingRow('deckCardShows', 'Deck card shows', 'Reveal the next card in the draw pile.', room)}</div>${room.isHost ? `<button class="primary wide" id="start" ${room.players.length < 2 ? 'disabled' : ''}>Start game <span>→</span></button>` : '<div class="waiting-note">Waiting for the host to start...</div>'}</div></section></main>`
  document.querySelector('#leave').addEventListener('click', () => { unlockAudio(); send('leave') })
  document.querySelector('#copy').addEventListener('click', async () => { await navigator.clipboard?.writeText(room.code); document.querySelector('#copy-status').textContent = 'Room code copied to clipboard.' })
  document.querySelectorAll('[data-setting]').forEach((input) => input.addEventListener('change', () => send('updateSettings', { settings: { [input.dataset.setting]: input.checked } })))
  document.querySelector('#start')?.addEventListener('click', () => { unlockAudio(); send('startGame') })
}
function renderGame() {
  const room = state.room; const top = room.topCard
  if (soundState.lastTurn !== room.currentPlayer) { if (room.currentPlayer === room.me) playTurnSound(); soundState.lastTurn = room.currentPlayer }
  app.innerHTML = `<main class="game-layout"><header class="topbar"><div class="wordmark"><span class="dot"></span> UNO <span class="game-code">ROOM ${room.code}</span></div><div class="game-tools"><span class="turn-label">${room.currentPlayer === room.me ? 'YOUR TURN' : `${escapeHtml(room.currentPlayerName)}'S TURN`}</span><button class="ghost" id="leave">Exit</button></div></header><section class="table"><div class="table-head"><div><p class="eyebrow">ROUND ${room.round}</p><h1>${room.currentPlayer === room.me ? 'Make your move.' : `${escapeHtml(room.currentPlayerName)} is thinking...`}</h1></div><div class="turn-order">${room.players.map((player) => `<span class="turn-avatar ${player.id === room.currentPlayer ? 'active' : ''}">${initials(player.name)}</span>`).join('')}</div></div>${room.lastUnoCall ? `<div class="uno-call-banner"><strong>UNO!</strong> ${escapeHtml(room.lastUnoCall.playerName)} called it.</div>` : ''}<div class="opponent-rail">${room.players.filter((player) => player.id !== room.me).map((player) => opponentPanel(player, room)).join('')}</div><div class="play-zone"><div class="deck-stack">${deckButton(room)}<small class="deck-label">${room.deckCount} cards left</small></div><div class="top-card-wrap"><div class="card face ${top.color}"><strong>${top.value}</strong><span>${symbol(top.value)}</span><b>${top.value}</b></div><small class="active-color"><i class="${room.activeColor}"></i> ${room.activeColor} is active</small></div></div>${room.pendingDraw ? `<div class="penalty-banner">${room.settings.cardStacking ? 'STACKED PENALTY' : 'DRAW PENALTY'} <strong>${room.pendingDraw} cards</strong> · ${room.settings.cardStacking ? 'play another +2/+4 or draw' : 'draw your cards'}</div>` : ''}<div class="hand-area"><div class="hand-heading"><span>YOUR HAND <b>${room.hand.length}</b></span>${room.currentPlayer === room.me ? '<small>Choose a matching color or wild card</small>' : '<small>Hang tight for your turn</small>'}</div>${room.currentPlayer === room.me && room.hand.length === 1 ? `<button class="uno-button ${room.unoCalled ? 'called' : ''}" id="yell-uno" ${room.unoCalled ? 'disabled' : ''}>${room.unoCalled ? 'UNO CALLED' : 'YELL UNO'}</button>` : ''}<div class="hand">${room.hand.map((card, index) => cardButton(card, index, room)).join('')}</div></div></section>${state.selectedColor ? colorPicker() : ''}<div class="toast ${state.error ? 'show' : ''}">${escapeHtml(state.error || '')}</div></main>`
  document.querySelector('#leave').addEventListener('click', () => { unlockAudio(); send('leave') })
  document.querySelector('#draw').addEventListener('click', () => { unlockAudio(); playDrawSound(); send('drawCard') })
  document.querySelector('#yell-uno')?.addEventListener('click', () => { unlockAudio(); send('yellUno') })
  document.querySelectorAll('[data-card]').forEach((button) => button.addEventListener('click', () => { unlockAudio(); const card = room.hand[Number(button.dataset.card)]; if (!canPlay(card, room)) { playRejectSound(); return } if (card.value === 'WILD' || card.value === '+4') { state.selectedColor = Number(button.dataset.card); renderGame() } else { playPlaceSound(); send('playCard', { index: Number(button.dataset.card) }) } }))
  document.querySelectorAll('[data-color]').forEach((button) => button.addEventListener('click', () => { unlockAudio(); playPlaceSound(); send('playCard', { index: state.selectedColor, color: button.dataset.color }); state.selectedColor = null }))
}
function settingRow(key, title, description, room) { return `<label class="setting-row"><span><strong>${title}</strong><small>${description}</small></span><input type="checkbox" data-setting="${key}" ${room.settings[key] ? 'checked' : ''} ${room.isHost ? '' : 'disabled'}><i></i></label>` }
function opponentPanel(player, room) { const backs = Array.from({ length: Math.min(player.cardCount, 7) }, (_, index) => `<i style="--offset:${index * 32}px"></i>`).join(''); return `<div class="opponent-panel ${room.currentPlayer === player.id ? 'active' : ''}"><div class="opponent-label"><span class="avatar">${initials(player.name)}</span><div><strong>${escapeHtml(player.name)}</strong><small>${player.cardCount} ${player.cardCount === 1 ? 'card' : 'cards'}</small></div></div><div class="opponent-cards">${backs}</div></div>` }
function deckButton(room) { const disabled = room.currentPlayer !== room.me ? 'disabled' : ''; const drawText = room.pendingDraw && room.settings.cardStacking ? `DRAW ${room.pendingDraw}` : 'DRAW'; if (room.settings.deckCardShows && room.deckPreview) return `<button class="deck deck-preview ${room.deckPreview.color}" id="draw" ${disabled}><strong>${room.deckPreview.value}</strong><span>${symbol(room.deckPreview.value)}</span><b>${room.deckPreview.value}</b></button>`; return `<button class="deck" id="draw" ${disabled}><span>UNO</span><b>7</b><small>${drawText}</small></button>` }
function cardButton(card, index, room) { const playable = canPlay(card, room); const highlighted = room.settings.cardSuggestions ? playable : true; return `<button class="card hand-card ${card.color} ${highlighted ? 'playable' : 'muted-card'}" data-card="${index}" ${room.currentPlayer !== room.me ? 'disabled' : ''}><strong>${card.value}</strong><span>${symbol(card.value)}</span><b>${card.value}</b></button>` }
function colorPicker() { return `<div class="color-picker"><p>Choose a color</p><button data-color="red">RED</button><button data-color="yellow">YELLOW</button><button data-color="green">GREEN</button><button data-color="blue">BLUE</button></div>` }
function canPlay(card, room) { if (room.pendingDraw && room.settings.cardStacking) return card.value === '+2' || card.value === '+4'; return card.color === 'wild' || card.color === room.activeColor || card.value === room.topCard.value }
function renderResult() { const won = state.room.winnerId === state.room.me; if (!soundState.resultPlayed) { if (won) playWinSound(); else playLoseSound(); soundState.resultPlayed = true } app.innerHTML = `<main class="result-screen ${won ? 'winner' : 'loser'}"><div class="result-card"><div class="result-art">${won ? '🦐' : '🥀'}</div><p class="eyebrow">GAME OVER</p><h1>${won ? 'Shrimply brilliant!' : 'Tough break.'}</h1><p>${won ? 'You cleared your hand and ruled the table.' : `${escapeHtml(state.room.winnerName)} took the win this round.`}</p><div class="result-badge">${won ? 'WINNER' : 'BETTER LUCK NEXT ROUND'}</div><button class="primary" id="result-exit">Back to lobby <span>→</span></button></div></main>`; document.querySelector('#result-exit').addEventListener('click', () => { soundState.resultPlayed = false; state.room = null; renderLobby(); send('leave') }) }
function renderCurrent() { if (!state.username) renderAuth(); else if (!state.room) renderLobby(); else if (state.room.status === 'waiting') renderRoom(); else if (state.room.status === 'finished') renderResult(); else renderGame() }
function initials(name) { return name.split(/\s+/).map((part) => part[0]).join('').slice(0, 2).toUpperCase() }
function symbol(value) { return value === 'SKIP' ? '⊘' : value === 'REVERSE' ? '↻' : value === '+2' || value === '+4' ? '+' : value === 'WILD' ? '✦' : value }
function setCookie(name, value, days) { document.cookie = `${name}=${encodeURIComponent(value)}; max-age=${days * 86400}; path=/; SameSite=Lax` }
function getCookie(name) { return document.cookie.split('; ').find((entry) => entry.startsWith(`${name}=`))?.split('=').slice(1).join('=') ? decodeURIComponent(document.cookie.split('; ').find((entry) => entry.startsWith(`${name}=`)).split('=').slice(1).join('=')) : '' }
function escapeHtml(value) { return String(value).replace(/[&<>'"]/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char])) }
